### ISSUE TITLE
Failed avatars break layout

### ISSUE THREAD

**Issue by wcoder** [Softeq/Kudos#131]
<img src="https://user-images.githubusercontent.com/766193/87872523-0ef50b00-c9c2-11ea-9abf-ec5e5d53276c.png" width="300">

**Comment by AlexandraMash** [comment]
@wcoder Could you add more details on how to reproduce this bug?

**Comment by wcoder** [comment]
- low battery
- bad network connection (wifi)

**Comment by SavikPavel** [comment]
Fixed
