### ISSUE TITLE
Sliver AppBar UI is broken on some devices

### ISSUE THREAD

**Issue by AlexandraMash** [Softeq/Kudos#142]
<img src="https://user-images.githubusercontent.com/24733826/88187684-84b9da80-cc3f-11ea-9cb6-8f0a7605552a.png" width="300"> <img src="https://user-images.githubusercontent.com/24733826/88187694-86839e00-cc3f-11ea-881c-9077e6e5d7da.png" width="300">

**Comment by AlexandraMash** [comment]
@wcoder Please, add device info

**Comment by wcoder** [comment]
Android
[Xiaomi Mi A3](https://www.gsmarena.com/xiaomi_mi_a3-9769.php)
